# Generated by Django 5.1.1 on 2024-10-09 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deshboard', '0002_alter_notes_options_homework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='in_finished',
            new_name='is_finished',
        ),
    ]
