# Generated by Django 5.1.1 on 2024-10-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deshboard', '0005_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='desc',
            field=models.CharField(default='No description', max_length=255),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
